# Generated by Django 3.0.3 on 2020-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCrime', '0003_auto_20200831_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missing_complaint',
            name='City',
            field=models.CharField(max_length=100),
        ),
    ]
