# Generated by Django 3.0.3 on 2020-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCrime', '0005_auto_20200901_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='DateofComplaint',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='missing_complaint',
            name='DateofComplaint',
            field=models.DateField(default=None),
        ),
    ]
